### PR TITLE
resubscribe functionality via API

### PR DESCRIPTION
**Pull request by andreibaca**
If the user is unsubscribed Zoho allows only resubscription via form.
The subscription response returns true for success but the message is "Contact belongs to Do-not-mail registry." and user does not receive any confirmation emails and is not subscribed again.

To allow re-subscription a specific parameter has to be added to the request url 
donotmail_resub=true

With this parameter the response message is the following 
"This is a Donotmail contact or removed contact,So the resubscribtion email is sent to the user. User needs to confirm to successfully subscribe."
And  user receives a resubscription confirmation email.

With this pull request resubscribe method is added that works.

### CODE REVIEW

**Comment by cappuc** [comment]
Hi @andreibaca 

Do you think it makes sense to always add the `donotmail_resub=true` parameter to the subscribe request?

If the subscribe response is successful even if the user is not actually subscribed, you have to check the message and then call the resubscribe method and this is not so intuitive.

If always adding the parameter is not a problem, I think that is better to add it to the subscribe request so it can handle both cases

**Comment by andreibaca** [comment]
I think it's better to offer more choice and document it. If someone wants to use donotmail_resub he can just use the resubscribe function instead of subscribe. I am not sure what problems could arise if we use this parameters for subscribe all the time since it is not documented, and could even change in the future which could result in errors.
We can just add a parameter to the subscribe method to allow resubscription when necessary.
Maybe even include the $optional_parameters in subscribe.

**Comment by andreibaca** [comment]
Actually I will test if it's ok to use resubscribe for new users.

**Comment by andreibaca** [comment]
It seems to simply work for new users when using donotmail_resub=true. May be I overengineered it. Just did not want to mess with existing functionality to make it backwards compatible.. :)
But I would still add the optional parameters for any future cases. It just makes the library more flexible.

**Comment by andreibaca** [comment]
I just thought of a case where the developer might want to confirm that the user really wants to resubscribe then we need 2 separate methods.

**Comment by andreibaca** [comment]
I have added some more functionality to get the list of subscribers and to count them. 
I forgot to create a new branch so it's in the same pull request.  Sorry for confusion and inconvenience. 
I have already tested it with a live zoho account and it works as expected.

**Comment by cappuc** [comment]
No problem!

Next week I'll review the changes and merge it.

**Pull request merged**
